export type SegmentTraits = {
  account_id?: null;
  account_type?: null;
  date_of_birth?: Date;
  digital_engagement_score?: number;
  email?: string;
  enterprise_id?: null;
  first_name?: string;
  funds_in_date?: null;
  funds_in_ind?: null;
  funds_out_date?: null;
  funds_out_ind?: null;
  ga_id?: string;
  invst_hm_lon_cstmr_ind?: boolean;
  // j_o_mcq_uc_5_behavioral_communications_v_1__customer_engagement_activities_men1n?: boolean;
  // j_o_mcq_uc_5_behavioral_communications_v_1__customer_engagement_activities_men1n_joined_at?: Date;
  // j_o_mcq_uc_5_behavioral_communications_v_1__exit_cjkts_key?: boolean;
  // j_o_mcq_uc_5_behavioral_communications_v_1__exit_cjkts_key_joined_at?: Date;
  // j_o_mcq_uc_5_behavioral_communications_v_1__mcq_customer_cjkts?: boolean;
  // j_o_mcq_uc_5_behavioral_communications_v_1__mcq_customer_cjkts_hidden_entry?: boolean;
  // j_o_mcq_uc_5_behavioral_communications_v_1__mcq_customer_cjkts_hidden_entry_joined_at?: Date;
  // j_o_mcq_uc_5_behavioral_communications_v_1__mcq_customer_cjkts_joined_at?: Date;
  // j_o_mcq_uc_5_behavioral_communications_v_1_copy__customer_engagement_activities_08c3i?: boolean;
  // j_o_mcq_uc_5_behavioral_communications_v_1_copy__customer_engagement_activities_08c3i_joined_at?: Date;
  // j_o_mcq_uc_5_behavioral_communications_v_1_copy__mcq_customer_9ji9q?: boolean;
  // j_o_mcq_uc_5_behavioral_communications_v_1_copy__mcq_customer_9ji9q_hidden_entry?: boolean;
  // j_o_mcq_uc_5_behavioral_communications_v_1_copy__mcq_customer_9ji9q_hidden_entry_joined_at?: Date;
  // j_o_mcq_uc_5_behavioral_communications_v_1_copy__mcq_customer_9ji9q_joined_at?: Date;
  // j_o_mcq_uc_5_behavioral_communications_v_2__customer_engagement_activities_zv1ep?: boolean;
  // j_o_mcq_uc_5_behavioral_communications_v_2__customer_engagement_activities_zv1ep_joined_at?: Date;
  // j_o_mcq_uc_5_behavioral_communications_v_2__exit_9kxsc_key?: boolean;
  // j_o_mcq_uc_5_behavioral_communications_v_2__exit_9kxsc_key_joined_at?: Date;
  // j_o_mcq_uc_5_behavioral_communications_v_2__mcq_customer_9kxsc?: boolean;
  // j_o_mcq_uc_5_behavioral_communications_v_2__mcq_customer_9kxsc_hidden_entry?: boolean;
  // j_o_mcq_uc_5_behavioral_communications_v_2__mcq_customer_9kxsc_hidden_entry_joined_at?: Date;
  // j_o_mcq_uc_5_behavioral_communications_v_2__mcq_customer_9kxsc_joined_at?: Date;
  // j_o_mcq_uc_5_behavioral_communications_v_3__customer_engagement_activities_4wtod?: boolean;
  // j_o_mcq_uc_5_behavioral_communications_v_3__customer_engagement_activities_4wtod_joined_at?: Date;
  // j_o_mcq_uc_5_behavioral_communications_v_3__mcq_customer_p492v?: boolean;
  // j_o_mcq_uc_5_behavioral_communications_v_3__mcq_customer_p492v_hidden_entry?: boolean;
  // j_o_mcq_uc_5_behavioral_communications_v_3__mcq_customer_p492v_hidden_entry_joined_at?: Date;
  // j_o_mcq_uc_5_behavioral_communications_v_3__mcq_customer_p492v_joined_at?: Date;
  last_name?: string;
  latest_balance?: null;
  marketing_engagement_score?: number;
  ofst_hldng_ind?: boolean;
  ownr_ocpd_hm_lon_cstmr_ind?: boolean;
  phone_number?: string;
  prsnl_bnkng_cstmr_ind?: boolean;
  prvt_bnkng_cstmr_ind?: boolean;
  segment_id?: string;
  txn_flight_date?: null;
  txn_flight_ind?: null;

  animal?: string;
  music_preference?: string;
  favourite_colour?: string;
};
